# Create macros for the fields of a TrackMan CSV file
ID = "PitcherId"
NAME = "Pitcher"
THROWING_HAND = "PitcherThrows"
SET = "PitcherSet"
PITCH_TYPE = "TaggedPitchType"
VELOCITY = "RelSpeed"
VERTICAL_BREAK = "InducedVertBreak"
HORIZONTAL_BREAK = "HorzBreak"
SPIN_RATE = "SpinRate"
SPIN_AXIS = "SpinAxis"
VERITCAL_APPROACH = "VertApprAngle"
HORIZONTAL_POSITION = "PlateLocSide"
VERTICAL_POSITION = "PlateLocHeight"
RELEASE_HEIGHT = "RelHeight"
RELEASE_SIDE = "RelSide"
EXTENSION = "Extension"
